language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "12"

os:
  - linux
  - osx
  - windows

install:
  # - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Install dependencies and build
  - npm install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm test
